;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-raise-sexp
        counsel-M-x
        fixup-whitespace
        indent-for-tab-command
        minibuffer-keyboard-quit
        mouse-set-region
        move-text-up
        org-cycle
        org-self-insert-command
        paredit-backward
        paredit-backward-down
        paredit-backward-kill-word
        paredit-backward-up
        paredit-close-round
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-forward-up
        paredit-meta-doublequote
        paredit-open-round
        paredit-open-square
        paredit-reindent-defun
        paredit-semicolon
        paredit-splice-sexp
        repeat
        sp-backward-delete-char
        sp-kill-region
        transpose-sexps
        zop-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        ))
