;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        move-text-up
        org-cycle
        org-self-insert-command
        paredit-backward
        paredit-forward-slurp-sexp
        paredit-open-round
        paredit-reindent-defun
        sp-backward-delete-char
        sp-kill-region
        transpose-sexps
        zop-to-char
        indent-for-tab-command
        minibuffer-keyboard-quit
        mouse-set-region
        paredit-forward-delete
        paredit-open-square
        repeat
        ))

(setq mc/cmds-to-run-once
      '())
